/**
 * This file was auto-generated by Payload.
 * For manual type regeneration run: npx payload generate:types
 */

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  collections: {
    users: User
    countdowns: Countdown
    'exam-results': ExamResult
    media: Media
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  globals: {
    'site-settings': SiteSettings
  }
  locale: null
  user: User & {
    collection: 'users'
  }
}

export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}

export interface User {
  id: number
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  updatedAt: string
  createdAt: string
  enableAPIKey?: boolean | null
  apiKey?: string | null
  apiKeyIndex?: string | null
}

export interface Countdown {
  id: number
  title: string
  subtitle?: string | null
  description?: string | null
  targetDate: string
  targetTime: string
  backgroundImage?: (number | null) | Media
  themeColor?: string | null
  buttonText?: string | null
  buttonLink?: string | null
  expiredMessage?: string | null
  active?: boolean | null
  updatedAt: string
  createdAt: string
}

export interface ExamResult {
  id: number
  title: string
  subtitle?: string | null
  description?: string | null
  resultImage: number | Media
  resultExcel?: (number | null) | Media
  backgroundImage?: (number | null) | Media
  publishDate?: string | null
  active?: boolean | null
  updatedAt: string
  createdAt: string
}

export interface Media {
  id: number
  alt?: string | null
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
  sizes?: {
    thumbnail?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    large?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
  }
}

export interface SiteSettings {
  id: number
  activeContentType: 'countdown' | 'exam-results'
  activeCountdown?: (number | null) | Countdown
  activeExamResult?: (number | null) | ExamResult
  siteName?: string | null
  siteDescription?: string | null
  favicon?: (number | null) | Media
  updatedAt?: string | null
  createdAt?: string | null
}

export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?: Record<string, unknown> | unknown[] | string | number | boolean | null
  updatedAt: string
  createdAt: string
}

export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
